source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'rails'
gem 'pg'
gem 'puma'
gem 'redis'
gem 'bcrypt'
gem 'bootsnap', require: false
gem 'rack-cors'
gem 'redis-rails'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'jwt'
gem 'awesome_print'
gem 'jsonapi-serializer'
gem 'pagy'
gem 'pundit'
gem 'fcm'
gem 'firebase'
gem 'firebase_dynamic_link'
gem 'phone'
gem 'phonelib'
gem 'easy_translate'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'carrierwave-aws'
gem 'rswag-api'
gem 'rswag-ui'
gem 'rubocop'
gem 'traco'
gem 'activerecord-postgis-adapter'
gem 'apple_id'
gem 'google-id-token'
gem 'httparty'
gem 'simple_command'
gem 'dotenv'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rswag-specs'
end

group :development do
  gem 'annotate'
  gem 'bullet'
  gem 'listen'
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers', '~> 4.0'
end
